sprint4-team10/Rolling

src/components/CreateButton/CreateBtn.js, src/components/CreateButton/index.jsx, src/components/Navbar.jsx, src/pages/compononts/CreateCircleButton/ButtonIcon.js, src/pages/compononts/CreateCircleButton/index.jsx
**동일한 속성을 가진 기본 버튼 컴포넌트 구현**
: 사용하는 곳에 따라 속성값을 지정해서 사용할 수 있도록 prop으로 내려줌
- styled component에서 prop을 사용해서 내려주는 것이 조금 익숙해졌다.
- 재사용을 고려해서 만들기 위해서는, 제작 전에 어떤 요소를 prop으로 받아서 유동적으로 사용할 지 미리 구조화하고 시작해야겠다고 생각했다.
=> ✨ [유경] feat : button 컴포넌트 생성 #14

src/App.jsx, src/pages/Post.jsx, src/pages/PostPage/component/ColorBox.js, src/pages/PostPage/index.jsx
**Post 페이지 구현**
: 컴포넌트로 분리하지 않고, 선 구현 후 컴포넌트로 분리할 예정
- input 및 styled Component를 분리해서 재사용
- 추후에 컴포넌트로 제작해서 요소를 끌어와야 됨
- 클릭 시, 원형 아이콘으로 선택된 색상 표시해야 함
=> ✨ [유경] feat : Post페이지 구현 (컴포넌트 분리X) #16

src/api/api.js, src/components/Reaction/index.jsx, src/components/Senders/index.jsx, src/pages/Paper.jsx, src/pages/compononts/PaperHeader/index.jsx, src/util/formatDate.js
- api 폴더 추가
- senders 컴포넌트 생성
- reaction 컴포넌트 생성
=> :sparkles: API 연동

.eslintrc, package-lock.json, package.json, src/api/api.js, src/components/PopOver/index.jsx, src/components/PopOverIcons/index.jsx, src/components/Reaction/index.jsx, src/components/ReactionAddButton/index.jsx, src/hooks/useHandleOutsideClick.js, src/hooks/usePopOver.js, src/pages/Paper.jsx, src/pages/compononts/PaperHeader/index.jsx
- popOver 관련 커스텀 훅 생성
- useHandleClickOutSide 커스텀 훅 생성
- react-emoji-picker 라이브러리 사용 (https://github.com/ealush/emoji-picker-react)
=> :sparkles: 페이퍼 페이지 reaction 기능 완성

src/components/ReactionsPopOver/index.jsx, src/components/SharePopOver/index.jsx, src/hooks/usePopOver.js, src/pages/compononts/CardList/index.jsx, src/pages/compononts/PaperHeader/index.jsx
=> :sparkles: [태진] feat: share popOver 구현 URL 복사 기능 구현 #24

src/pages/compononts/CardList/index.jsx, src/pages/compononts/CreateCircleButton/ButtonIcon.js, src/pages/compononts/CreateCircleButton/index.jsx, src/pages/compononts/MessageCard/MessageCard.jsx
: 페이지에 포함되어 있던 카드 컴포넌트 분리 후 적용
-> img : background-image로 처리
close #11
=> ✨ [유경] feat : MessageCard 컴포넌트 제작 및 적용 #11

src/api/api.js, src/components/Reaction/index.jsx, src/components/Senders/index.jsx, src/pages/List/List.jsx, src/pages/List/components/Card/Card/Card.jsx, src/pages/List/components/Card/CardContent/CardContent.jsx
* 필요한 데이터를 띄우고 UI 완성
close #37
=> ✨[승훈]feat: 리스트페이지 데이터 띄우기 및 디자인#37

src/components/Modal/index.jsx, src/components/Navbar.jsx, src/components/Toast/index.jsx, src/hooks/useModal.js, src/pages/compononts/MessageCard/MessageCard.jsx, src/pages/compononts/PaperHeader/index.jsx
=> :sparkles: [태진] feat: 모달 컴포넌트 구현 및 적용 #25

src/components/RelationshipBadge/RelationshipBadge.jsx, src/components/RelationshipBadge/index.js, src/pages/compononts/MessageCard/MessageCard.jsx
- 기존에 COLOR 변수를 따로 만들어서 적용했던 색상들을 utils 폴더 내에 color를 활용해서 파일을 줄였습니다. 
- rem수치를 조정했습니다 !!
- message card에서 뱃지를 확인할 수 있도록 적용했습니다.
rem 자동 변환기 쓰지 마세요
=> ♻️ [승아] refactor: 불필요한 파일 삭제 및 rem수치 조정 #46

package-lock.json, package.json, public/index.html, src/components/TextField/Dropdown/Dropdown.jsx, src/components/TextField/Dropdown/index.js, src/components/TextField/Input/Input.js, src/components/TextField/Input/index.js, src/components/TextField/TextEditor/TextEditor.jsx, src/components/TextField/TextEditor/index.js, src/components/TextField/TextFields.jsx, src/components/TextField/index.js
1. 사용할 컴포넌트가 Input, Dropdown, TextEditor 인지 확인
2. prop으로 무엇을 내려줘야할지 확인해본다.
- Input 사용시 
- textFieldType으로 Input을 적어줌
- 원하는 placeholder 적어줌
- width값은 기본값으로 32rem이 적용되어있음, 만약 width="72rem"을하면 72rem로 적용되고 width=""이면 기본값 적용
- disabled를 사용하고싶다면 disabled="disabled"
- dropdown 사용시
- textFieldType으로 Dropdown을 적어줌
- defaultValue="원하는 값"
- options={OPTIONS}
- width값은 input과 똑같음
- disabled는 미완성
- TextEditor 미완성
- 추후에 수정하고 보완을 할 것이다.
=> ✨[승훈]feat: TextFields 컴포넌트#48

src/components/Buttons/Buttons.jsx, src/components/Buttons/ButtonsStyled.js
: Buttons 컴포넌트의 개선점 중 하나인 클릭 시 꿈틀거림 문제 개선
: 조건에 따라 disabled 될 수 있도록 prop 추가 함
=> 🐛 [유경] Button 컴포넌트 active될 때 꿈틀거리는 문제 개선

src/pages/List/List.jsx, src/pages/List/components/Card/Card/Card.jsx, src/pages/List/components/Card/CardList/CardLIst.jsx
- 슬라이더 구현
- List페이지에서 paper페이지 이동 구현
=> :sparkles: [태진] feat: List페이지 slider 구현

src/App.jsx, src/api/api.js, src/components/Buttons/Buttons.jsx, src/components/deleteModal/deleteModal.jsx, src/components/deleteModal/index.js, src/pages/Edit.jsx, src/pages/Paper.jsx, src/pages/compononts/CardList/index.jsx, src/pages/compononts/EditCard/EditCard.jsx, src/pages/compononts/EditCard/index.js
- 버튼 onClick props 추가
- 삭제 modal 구현
=> :sparkles: [태진] feat: 편집 페이지 구현

src/components/Buttons/AddButton/AddButton.jsx, src/components/Buttons/AddButton/index.js, src/components/Buttons/ArrowButton/ArrowButton.jsx, src/components/Buttons/ArrowButton/index.js
Arrow Button 컴포넌트를 구현했다.
close #18
=> ✨ [유경] feat : ArrowButton 컴포넌트 생성 #18

src/pages/PostPage/Post.jsx
: Post 페이지에서 Toggle Button focus일 때 style 추가
-> hover일 때의 style도 임의로 지정해 줌
- 추후에는 컴포넌트로 따로 분리하고 싶다.
=> 💄 [유경] design : Post페이지의 ToggleButton hover 및 focus 디자인 수정

src/pages/PostPage/Post.jsx, src/pages/PostPage/component/BackgroundOption/BackgroundOption.jsx
1) 불필요한 로직 제거 (styled component 미숙.....)
2) ToggleButton active 상태 반영
3) 선택된 background 종류 체크 표시로 확인 가능
- styled component에서 프롭을 활용하는 방법을 깨달았다...!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
- 이전에 작업했던 부분들도 오늘 알게 된 방법으로 리팩토링 할 수 있을 것 같다.
- 생성하기 버튼 disabled 된 상태에서도 hover이나 focus가 된다. 이것도 해결해야 함
=> ♻️ [유경] refactor : 불필요한 로직 제거 및 선택된 BackgroundType 버튼으로 확인 가능

src/components/Senders/index.jsx, src/pages/List/components/Card/Card/Card.jsx
카트 컴포넌트: 불필요한 z-index제거 (리팩토링)
카트 컴포넌트: 패턴이미지가 카드 밖으로 빠져나오는 문제 해결 (리팩토링 & 버그)
senders 컴포넌트 이미지 찌그러지는 현상 제거 (버그)
=> :bug: [태진] fix: 카트 패턴 넘침 문제 해결 & senders 컴포넌트 이미지 비율 수정

src/App.jsx, src/api/api.js, src/components/TextField/TextFields.jsx, src/pages/Message.jsx, src/pages/Message/Message.jsx, src/pages/Message/component/EnterContent.jsx, src/pages/Message/component/FontSelect.jsx, src/pages/Message/component/PostInput.jsx, src/pages/Message/component/ProfileImageSelect.jsx, src/pages/Message/component/RelationshipSelect.jsx, src/pages/Message/component/index.js
=> ✨[승훈]feat: MessagePage

src/components/deleteModal/deleteModal.jsx, src/hooks/useHandleDeleteMessage.js, src/pages/compononts/CardList/index.jsx
- 메세지 삭제 시 새로고침 없이 반영되도록 함
- props drilling을 피하기 위해 커스텀 훅 구현
- 커스텀 훅 구현에 개인적으로 만족한다. 전역 상태 관리를 쓰지 않고도 원하는 기능을 구현할 수 있었다.
=> :zap: [태진] perf: 메시지 삭제시 새로고침 없이 반영 되도록 수정

src/pages/List/List.jsx
=> :lipstick: [태진] desing: List페이지 레이아웃 수정

src/api/api.js, src/components/Modal/index.jsx, src/components/TextField/Dropdown/Dropdown.jsx, src/components/TextField/TextEditor/TextEditor.jsx, src/components/TextField/TextFields.jsx, src/pages/Message/Message.jsx, src/pages/Message/component/FontSelect.jsx, src/pages/Message/component/ProfileImageSelect.jsx, src/pages/Message/component/RelationshipSelect.jsx, src/pages/compononts/CardList/index.jsx, src/pages/compononts/MessageCard/MessageCard.jsx
- 롤링페이퍼 페이지 AddButton 클릭시 message 페이지로 이동
- 카드 Content: html 태그 반영할 수 있도록 수정
- dangerouslySetInnerHTML 이용
```
<CardContents dangerouslySetInnerHTML={{ __html: content }} />
```
- 우리가 정한 규칙인 px대신 rem 신경써서 사용
=> :sparkles: [태진] feat: message 페이지 기능 구현

src/components/Buttons/AddButton/AddButton.jsx, src/components/Buttons/AddButton/AddButtonStyled.js, src/components/Buttons/ArrowButton/ArrowButton.jsx, src/components/Buttons/ArrowButton/ArrowButtonStyled.js, src/pages/PostPage/Post.jsx
- index.js는 있었지만, 스타일 컴포넌트를 styled.js 로 분리하고 있지 않았어서 파일 추가하여 분리함
=> ♻️ [유경] refactor : Add버튼 및 Arrow 버튼 styled 컴포넌트 분리

src/components/TextField/Dropdown/Dropdown.jsx, src/components/TextField/Input/Input.js, src/components/TextField/TextEditor/TextEditor.jsx, src/components/TextField/TextFields.jsx, src/pages/Message/Message.jsx, src/pages/Message/component/FontSelect.jsx, src/pages/Message/component/PostInput.jsx, src/pages/Message/component/ProfileImageSelect.jsx, src/pages/Message/component/RelationshipSelect.jsx
* 이름 입력 input에 아무것도 입력하지 않았을때 에러메시지 띄움
* 상대와의 관계 및 폰트 선택의 목록중 선택 안했을때 에러메시지 띄움
* 드롭다운 열고 닫을때 화살표 방향 바뀜
* 반응형 구현
* 반응형을 추가해야 할 것 같다.
* 버튼 컴포넌트 반응형 추가되면 적용
=> ✨[승훈] feat: messagePage 기능 구현 마무리

src/components/Buttons/ButtonsStyled.js, src/pages/PostPage/PostStyled.js
inputBox, Button, ColorBox 등 미디어 쿼리를 사용해서 화면이 줄어들면 같이 줄어들 수 있도록 했습니다!
허나 아직 아쉬운 부분은, 화면이 줄어들 때, 색상 박스도 갯수와 줄에 맞춰서 같이 커졌다가 줄어들었다가 해야하는데.. 그걸 구현 못한게 아쉽습니다.. 
그리고 계속 뭔가 같은 부분을 맴돌고 있지만 답을 찾지 못했던 상태였어서 소요된  시간이 아깝기도..~~
헉 맞다 이슈 작성 안했어요
=> ⚡️ [승아] feat: postPage 반응형 구현

src/pages/PostPage/PostStyled.js
=> :bug: [태진] fix: post페이지 색상, 이미지 선택 부분 반응형 코드 수정

src/pages/PostPage/Post.jsx, src/pages/PostPage/PostStyled.js, src/pages/PostPage/constant.js
- post에서 color을 더 수월하게 전송하기 위해서 constant에서 색상값을 바꿔줌
=> ♻️ refactor : post페이지 코드 정리

src/pages/Message/Message.jsx
=> ✨[승훈]feat: messagePage 리퀘스트 중복 요청 방지

src/components/Buttons/ButtonsStyled.js, src/pages/List/List.jsx, src/pages/List/ListStyled.js, src/pages/List/components/Card/Card.jsx, src/pages/List/components/Card/CardStyled.js, src/pages/List/components/CardContent/CardContent.jsx, src/pages/List/components/CardContent/CardContentStyled.js
* listPage 버튼 반응형
* 콘솔에 오류찍히는 부분 수정
=> 🐛[승훈]fix: listPage console에 오류뜨는 부분 수정

src/components/ReactionAddButton/ReactionAddButton.jsx, src/components/ReactionsPopOver/ReactionsPopOver.jsx, src/components/deleteModal/deleteModal.jsx, src/pages/List/List.jsx, src/pages/Paper/Paper.jsx, src/pages/Paper/components/CardList/CardList.jsx, src/pages/PostPage/Post.jsx
=> :recycle: [태진] refactor: api 함수 호출시 try/catch 문 추가

src/pages/Paper/components/EditCard/EditCard.jsx, src/pages/Paper/components/EditCard/EditCardStyled.jsx, src/pages/Paper/components/MessageCard/MessageCard.jsx, src/pages/Paper/components/MessageCard/MessageCardStyled.jsx
=> :bug: [태진] fix: sender text 넘칠시 말줄임표 보이도록 수정

src/components/deleteModal/deleteModal.jsx, src/pages/Paper/components/CardList/CardList.jsx
롤링페이퍼 편집페이지에서 메시지 삭제 동작 안하는 오류 해결
=> :bug: [태진] fix: message 삭제시 오류 해결

src/pages/Message/Message.jsx, src/pages/Message/component/EnterContent/EnterContent.jsx, src/pages/Message/component/FontSelect/FontSelect.jsx, src/pages/Message/component/PostInput/PostInput.jsx, src/pages/Message/component/ProfileImageSelect/ProfileImageSelect.jsx, src/pages/Message/component/RelationshipSelect/RelationshipSelect.jsx
* messagePage에 사용하는 컴포넌트에 각각의 onChange 함수를 messagePage에 통합
=> ♻️ [승훈]refactor: onChange 함수 통합

src/api/api.js, src/pages/List/List.jsx
=> ♻️ [승훈]refactor: 새로추가된 API 함수를 사용하여 데이터 추가

.eslintrc, src/components/DeleteModal/DeleteModal.jsx, src/pages/Paper/Paper.jsx, src/pages/Paper/components/Card/Card.jsx, src/pages/Paper/components/CardList/CardList.jsx
메시지 삭제 시 Senders Count 변화하도록 수정
=> :bug: [태진] fix 메시지 삭제시 Senders Count 변경

src/components/TextField/Dropdown/Dropdown.jsx, src/components/TextField/Dropdown/DropdownStyled.js, src/pages/Message/components/FontSelect/FontSelect.jsx
* 너비에 따라 드롭다운목록 열리는 위치 변경
* fontSelect options value 추가
=> ✨[승훈]feat: 너비에 따라 드롭다운목록 열리는 위치 변경

src/pages/Paper/components/Card/Card.jsx, src/pages/Paper/components/Card/CardStyled.js, src/pages/Paper/components/CardList/CardList.jsx, src/styles/FontStyles.js
=> ✨[승훈]feat: 선택한 폰트 적용시키는 기능

package-lock.json, package.json, src/components/Loading/Loading.jsx, src/components/Loading/LoadingStyled.js, src/components/Loading/index.js, src/pages/List/List.jsx
=> ✨[승훈]feat: Loading 기능 구현
